# Generated by Django 2.2.19 on 2021-04-02 22:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20210402_1832'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customtext',
            name='fdfbdf',
        ),
        migrations.RemoveField(
            model_name='customtext',
            name='titlevbxc',
        ),
    ]
